(deftheme monochromatic-green
  "Created 2016-10-24.")

(custom-theme-set-faces
 'monochromatic-green
 '(default ((t (:inherit nil :stipple nil :background "black" :foreground "#61CE3C" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 1 :width normal :foundry "default" :family "default"))))
 '(cursor ((t (:background "#96CBFE"))))
 '(minibuffer-prompt ((t (:background "black" :foreground "#61CE3C"))))
 '(highlight ((t (:background "DarkOrange"))))
 '(region ((t (:background "#7F073F"))))
 '(trailing-whitespace ((((class color) (background light)) (:background "red1")) (((class color) (background dark)) (:background "red1")) (t (:inverse-video t))))
 '(font-lock-comment-delimiter-face ((default (:inherit (font-lock-comment-face)))))
 '(font-lock-comment-face ((t (:slant italic :foreground "#8B8989"))))
 '(font-lock-doc-face ((t (:slant italic :foreground "white" :background "grey10"))))
 '(font-lock-preprocessor-face ((t (:foreground "gray57"))))
 '(font-lock-string-face ((t (:foreground "color-46"))))
 '(font-lock-warning-face ((t (:weight bold :foreground "Pink"))))
 '(button ((t (:inherit (link)))))
 '(link ((((class color) (min-colors 88) (background light)) (:underline (:color foreground-color :style line) :foreground "RoyalBlue3")) (((class color) (background light)) (:underline (:color foreground-color :style line) :foreground "blue")) (((class color) (min-colors 88) (background dark)) (:underline (:color foreground-color :style line) :foreground "cyan1")) (((class color) (background dark)) (:underline (:color foreground-color :style line) :foreground "cyan")) (t (:inherit (underline)))))
 '(link-visited ((default (:inherit (link))) (((class color) (background light)) (:foreground "magenta4")) (((class color) (background dark)) (:foreground "violet"))))
 '(header-line ((default (:inherit (mode-line))) (((type tty)) (:underline (:color foreground-color :style line) :inverse-video nil)) (((class color grayscale) (background light)) (:box nil :foreground "grey20" :background "grey90")) (((class color grayscale) (background dark)) (:box nil :foreground "grey90" :background "grey20")) (((class mono) (background light)) (:underline (:color foreground-color :style line) :box nil :inverse-video nil :foreground "black" :background "white")) (((class mono) (background dark)) (:underline (:color foreground-color :style line) :box nil :inverse-video nil :foreground "white" :background "black"))))
 '(tooltip ((((class color)) (:inherit (variable-pitch) :foreground "black" :background "lightyellow")) (t (:inherit (variable-pitch)))))
 '(mode-line ((t (:foreground "#4c83ff" :background "gray10"))))
 '(mode-line-buffer-id ((t (:weight bold))))
 '(mode-line-emphasis ((t (:weight bold))))
 '(mode-line-highlight ((((class color) (min-colors 88)) (:box (:line-width 2 :color "grey40" :style released-button))) (t (:inherit (highlight)))))
 '(mode-line-inactive ((t (:foreground "gray30" :background "gray10"))))
 '(isearch ((t (:foreground "black" :background "deep pink"))))
 '(isearch-fail ((t (:background "red4"))))
 '(lazy-highlight ((t (:foreground "black" :background "yellow"))))
 '(match ((t (:background "blackn" :foreground "deep pink"))))
 '(next-error ((t (:foreground "black" :background "deep pink"))))
 '(query-replace ((t (:background "gray10")))))

(provide-theme 'monochromatic-green)
